<?

$smiles = Array(
"/:1:/","/:2:/",
"/:3:/","/:4:/",
"/:5:/","/:6:/",
"/:7:/","/:8:/",
"/:9:/","/:10:/",
"/:11:/","/:12:/",
"/:13:/","/:14:/",
"/:15:/","/:16:/",
"/:17:/","/:18:/",
"/:19:/","/:20:/",
"/:21:/","/:22:/",
"/:23:/","/:24:/",
"/:25:/","/:26:/",
"/:27:/","/:28:/",
"/:29:/","/:30:/",
"/:31:/","/:32:/",
"/:33:/","/:34:/",
"/:35:/","/:36:/",
"/:37:/","/:38:/",
"/:39:/","/:40:/",
"/:41:/","/:42:/",
"/:43:/","/:44:/",
"/:45:/","/:46:/",
"/:47:/","/:48:/",
"/:49:/","/:50:/",
"/:51:/","/:52:/",
"/:53:/","/:54:/",
"/:55:/","/:56:/",
"/:57:/","/:58:/",
"/:59:/","/:60:/",
"/:61:/","/:62:/",
"/:63:/","/:64:/",
"/:65:/","/:66:/",
"/:67:/","/:68:/",
"/:69:/","/:70:/",
"/:71:/","/:72:/",
"/:73:/","/:74:/",
"/:75:/","/:76:/",
"/:77:/","/:78:/",
"/:79:/","/:80:/",
"/:81:/","/:82:/",
"/:83:/","/:84:/",
"/:85:/","/:86:/",
"/:87:/","/:88:/",
"/:89:/","/:90:/",
"/:91:/","/:92:/",
"/:93:/","/:94:/",
"/:95:/","/:96:/",
"/:97:/","/:98:/",
"/:101:/","/:102:/",
"/:103:/","/:104:/",
"/:105:/","/:106:/",
"/:107:/","/:108:/",
"/:109:/","/:110:/",
"/:111:/","/:112:/",
"/:113:/","/:114:/",
"/:115:/","/:116:/",
"/:117:/","/:118:/",
"/:119:/","/:120:/",
"/:121:/","/:122:/",
"/:123:/","/:124:/",
"/:125:/","/:126:/",
"/:127:/","/:128:/",
"/:129:/","/:130:/",
"/:131:/","/:132:/",
"/:133:/","/:134:/",
"/:135:/","/:136:/",
"/:137:/","/:138:/",
"/:139:/","/:140:/",
"/:141:/","/:142:/",
"/:143:/","/:144:/",
"/:145:/","/:146:/",
"/:147:/","/:148:/",
"/:149:/","/:150:/",
"/:151:/","/:152:/",
"/:153:/","/:154:/",
"/:155:/","/:156:/",
"/:157:/","/:158:/",
"/:159:/","/:160:/",
"/:161:/","/:162:/",
"/:163:/","/:164:/",
"/:165:/","/:166:/",
"/:167:/","/:168:/",
"/:169:/",
"/:170:/","/:171:/",
"/:172:/","/:173:/",
"/:174:/","/:175:/",
"/:176:/","/:177:/",
"/:178:/","/:179:/",
"/:180:/","/:181:/",
"/:182:/","/:183:/",
"/:184:/","/:185:/",
"/:186:/","/:187:/",
"/:188:/","/:189:/",
"/:190:/","/:191:/",
"/:192:/","/:193:/",
"/:194:/","/:195:/",
"/:196:/","/:197:/",
"/:198:/","/:199:/",
"/:200:/","/:201:/",
"/:202:/");


$smiles2 = Array(


"<img style=\"cursor:pointer;\" onclick=S(\"1\") 

 src=img/smiles/smiles_1.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"2\") src=img/smiles/smiles_2.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"3\") src=img/smiles/smiles_3.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"4\") src=img/smiles/smiles_4.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"5\") src=img/smiles/smiles_5.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"6\") src=img/smiles/smiles_6.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"7\") src=img/smiles/smiles_7.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"8\") src=img/smiles/smiles_8.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"9\") src=img/smiles/smiles_9.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"10\") src=img/smiles/smiles_10.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"11\") src=img/smiles/smiles_11.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"12\") src=img/smiles/smiles_12.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"13\") src=img/smiles/smiles_13.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"14\") src=img/smiles/smiles_14.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"15\") src=img/smiles/smiles_15.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"16\") src=img/smiles/smiles_16.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"17\") src=img/smiles/smiles_17.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"18\") src=img/smiles/smiles_18.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"19\") src=img/smiles/smiles_19.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"20\") src=img/smiles/smiles_20.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"21\") src=img/smiles/smiles_21.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"22\") src=img/smiles/smiles_22.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"23\") src=img/smiles/smiles_23.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"24\") src=img/smiles/smiles_24.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"25\") src=img/smiles/smiles_25.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"26\") src=img/smiles/smiles_26.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"27\") src=img/smiles/smiles_27.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"28\") src=img/smiles/smiles_28.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"29\") src=img/smiles/smiles_29.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"30\") src=img/smiles/smiles_30.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"31\") src=img/smiles/smiles_31.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"32\") src=img/smiles/smiles_32.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"33\") src=img/smiles/smiles_33.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"34\") src=img/smiles/smiles_34.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"35\") src=img/smiles/smiles_35.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"36\") src=img/smiles/smiles_36.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"37\") src=img/smiles/smiles_37.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"38\") src=img/smiles/smiles_38.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"39\") src=img/smiles/smiles_39.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"40\") src=img/smiles/smiles_40.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"41\") src=img/smiles/smiles_41.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"42\") src=img/smiles/smiles_42.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"43\") src=img/smiles/smiles_43.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"44\") src=img/smiles/smiles_44.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"45\") src=img/smiles/smiles_45.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"46\") src=img/smiles/smiles_46.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"47\") src=img/smiles/smiles_47.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"48\") src=img/smiles/smiles_48.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"49\") src=img/smiles/smiles_49.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"50\") src=img/smiles/smiles_50.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"51\") src=img/smiles/smiles_51.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"52\") src=img/smiles/smiles_52.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"53\") src=img/smiles/smiles_53.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"54\") src=img/smiles/smiles_54.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"55\") src=img/smiles/smiles_55.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"56\") src=img/smiles/smiles_56.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"57\") src=img/smiles/smiles_57.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"58\") src=img/smiles/smiles_58.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"59\") src=img/smiles/smiles_59.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"60\") src=img/smiles/smiles_60.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"61\") src=img/smiles/smiles_61.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"62\") src=img/smiles/smiles_62.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"63\") src=img/smiles/smiles_63.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"64\") src=img/smiles/smiles_64.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"65\") src=img/smiles/smiles_65.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"66\") src=img/smiles/smiles_66.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"67\") src=img/smiles/smiles_67.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"68\") src=img/smiles/smiles_68.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"69\") src=img/smiles/smiles_69.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"70\") src=img/smiles/smiles_70.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"71\") src=img/smiles/smiles_71.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"72\") src=img/smiles/smiles_72.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"73\") src=img/smiles/smiles_73.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"74\") src=img/smiles/smiles_74.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"75\") src=img/smiles/smiles_75.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"76\") src=img/smiles/smiles_76.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"77\") src=img/smiles/smiles_77.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"78\") src=img/smiles/smiles_78.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"79\") src=img/smiles/smiles_79.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"80\") src=img/smiles/smiles_80.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"81\") src=img/smiles/smiles_81.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"82\") src=img/smiles/smiles_82.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"83\") src=img/smiles/smiles_83.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"84\") src=img/smiles/smiles_84.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"85\") src=img/smiles/smiles_85.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"86\") src=img/smiles/smiles_86.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"87\") src=img/smiles/smiles_87.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"88\") src=img/smiles/smiles_88.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"89\") src=img/smiles/smiles_89.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"90\") src=img/smiles/smiles_90.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"91\") src=img/smiles/smiles_91.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"92\") src=img/smiles/smiles_92.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"93\") src=img/smiles/smiles_93.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"94\") src=img/smiles/smiles_94.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"95\") src=img/smiles/smiles_95.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"96\") src=img/smiles/smiles_96.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"97\") src=img/smiles/smiles_97.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"98\") src=img/smiles/smiles_98.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"101\") src=img/smiles/smiles_101.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"102\") src=img/smiles/smiles_102.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"103\") src=img/smiles/smiles_103.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"104\") src=img/smiles/smiles_104.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"105\") src=img/smiles/smiles_105.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"106\") src=img/smiles/smiles_106.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"107\") src=img/smiles/smiles_107.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"108\") src=img/smiles/smiles_108.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"109\") src=img/smiles/smiles_109.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"110\") src=img/smiles/smiles_110.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"111\") src=img/smiles/smiles_111.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"112\") src=img/smiles/smiles_112.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"113\") src=img/smiles/smiles_113.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"114\") src=img/smiles/smiles_114.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"115\") src=img/smiles/smiles_115.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"116\") src=img/smiles/smiles_116.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"117\") src=img/smiles/smiles_117.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"118\") src=img/smiles/smiles_118.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"119\") src=img/smiles/smiles_119.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"120\") src=img/smiles/smiles_120.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"121\") src=img/smiles/smiles_121.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"122\") src=img/smiles/smiles_122.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"123\") src=img/smiles/smiles_123.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"124\") src=img/smiles/smiles_124.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"125\") src=img/smiles/smiles_125.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"126\") src=img/smiles/smiles_126.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"127\") src=img/smiles/smiles_127.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"128\") src=img/smiles/smiles_128.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"129\") src=img/smiles/smiles_129.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"130\") src=img/smiles/smiles_130.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"131\") src=img/smiles/smiles_131.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"132\") src=img/smiles/smiles_132.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"133\") src=img/smiles/smiles_133.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"134\") src=img/smiles/smiles_134.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"135\") src=img/smiles/smiles_135.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"136\") src=img/smiles/smiles_136.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"137\") src=img/smiles/smiles_137.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"138\") src=img/smiles/smiles_138.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"139\") src=img/smiles/smiles_139.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"140\") src=img/smiles/smiles_140.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"141\") src=img/smiles/smiles_141.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"142\") src=img/smiles/smiles_142.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"143\") src=img/smiles/smiles_143.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"144\") src=img/smiles/smiles_144.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"145\") src=img/smiles/smiles_145.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"146\") src=img/smiles/smiles_146.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"147\") src=img/smiles/smiles_147.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"148\") src=img/smiles/smiles_148.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"149\") src=img/smiles/smiles_149.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"150\") src=img/smiles/smiles_150.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"151\") src=img/smiles/smiles_151.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"152\") src=img/smiles/smiles_152.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"153\") src=img/smiles/smiles_153.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"154\") src=img/smiles/smiles_154.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"155\") src=img/smiles/smiles_155.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"156\") src=img/smiles/smiles_156.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"157\") src=img/smiles/smiles_157.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"158\") src=img/smiles/smiles_158.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"159\") src=img/smiles/smiles_159.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"160\") src=img/smiles/smiles_160.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"161\") src=img/smiles/smiles_161.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"162\") src=img/smiles/smiles_162.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"163\") src=img/smiles/smiles_163.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"164\") src=img/smiles/smiles_164.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"165\") src=img/smiles/smiles_165.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"166\") src=img/smiles/smiles_166.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"167\") src=img/smiles/smiles_167.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"168\") src=img/smiles/smiles_168.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"169\") src=img/smiles/smiles_169.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"170\") src=img/smiles/smiles_170.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"171\") src=img/smiles/smiles_171.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"172\") src=img/smiles/smiles_172.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"173\") src=img/smiles/smiles_173.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"174\") src=img/smiles/smiles_174.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"175\") src=img/smiles/smiles_175.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"176\") src=img/smiles/smiles_176.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"177\") src=img/smiles/smiles_177.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"178\") src=img/smiles/smiles_178.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"179\") src=img/smiles/smiles_179.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"180\") src=img/smiles/smiles_180.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"181\") src=img/smiles/smiles_181.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"182\") src=img/smiles/smiles_182.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"183\") src=img/smiles/smiles_183.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"184\") src=img/smiles/smiles_184.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"185\") src=img/smiles/smiles_185.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"186\") src=img/smiles/smiles_186.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"187\") src=img/smiles/smiles_187.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"188\") src=img/smiles/smiles_188.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"189\") src=img/smiles/smiles_189.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"190\") src=img/smiles/smiles_190.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"191\") src=img/smiles/smiles_191.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"192\") src=img/smiles/smiles_192.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"193\") src=img/smiles/smiles_193.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"194\") src=img/smiles/smiles_194.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"195\") src=img/smiles/smiles_195.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"196\") src=img/smiles/smiles_196.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"197\") src=img/smiles/smiles_197.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"198\") src=img/smiles/smiles_198.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"199\") src=img/smiles/smiles_199.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"200\") src=img/smiles/smiles_200.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"201\") src=img/smiles/smiles_201.gif>",
"<img style=\"cursor:pointer;\" onclick=S(\"202\") src=img/smiles/smiles_202.gif>");
$_GET['text'] = preg_replace($smiles, $smiles2, $_GET['text'],3);

?>